version: 0.1
loglevel: debug
storage:
  filesystem:
    rootdirectory: /var/lib/docker-registry
http:
  addr: 0.0.0.0:5000
auth:
  token:
   # realm: http://portus.test.lan/v2/token
    realm: http://localhost:3000/v2/token
   # service: registry.test.lan
    service: localhost
   # issuer: portus.test.lan
    issuer: loclhost:3000
    rootcertbundle: /etc/registry/portus.crt
notifications:
  endpoints:
    - name: portus
      # url: http://portus.test.lan/v2/webhooks/events
      url: http://localhost:3000/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
